# Generated by Django 5.2.12 on 2026-04-29 00:08

import Medicos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Medico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("apellido", models.CharField(max_length=50)),
                ("fecha_de_inicio", models.DateField(auto_now_add=True)),
                (
                    "especialidad",
                    models.CharField(
                        choices=[
                            ("Corazon", "Cardiologo"),
                            ("Cerebro", "Neurologo"),
                            ("Huesos", "Traumatologo"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default=Medicos.models.generar_code, max_length=32, unique=True
                    ),
                ),
            ],
        ),
    ]
