# Generated by Django 5.2.12 on 2026-04-29 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DepartamentosMedicos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("nro_departamento", models.IntegerField(unique=True)),
                ("nro_empleados", models.IntegerField(null=True)),
                ("fecha_de_creacion", models.DateField(auto_now_add=True)),
                ("email_dpto", models.EmailField(max_length=254)),
            ],
        ),
    ]
